name: pet_gram
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Uyumlu versiyonlar
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.6

  # State Management
  provider: ^6.1.1

  # UI & Media
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  flutter_image_compress: ^2.1.0
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  file_picker: ^6.1.1

  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  record: ^5.0.4
  
  # Icons & Animations
  font_awesome_flutter: ^10.6.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  agora_rtc_engine: ^6.2.0
  permission_handler: ^11.0.1
  
  # Other
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700