// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArkxc3sNimm2YklQkJFRIb-lXi0yKQvLM',
    appId: '1:1016858793515:web:14c50a7a017b4434fefc6e',
    messagingSenderId: '1016858793515',
    projectId: 'petgram-26653',
    authDomain: 'petgram-26653.firebaseapp.com',
    storageBucket: 'petgram-26653.firebasestorage.app',
    measurementId: 'G-TTTV8H6X6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nx2SXawbfeyPICq8jjE5rahGBpP4btQ',
    appId: '1:1016858793515:android:5fd74824810a1fd1fefc6e',
    messagingSenderId: '1016858793515',
    projectId: 'petgram-26653',
    storageBucket: 'petgram-26653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQhroJ61rnqYeCg24UxvmI-lzTV51POg',
    appId: '1:1016858793515:ios:d7edda7b24aa47d1fefc6e',
    messagingSenderId: '1016858793515',
    projectId: 'petgram-26653',
    storageBucket: 'petgram-26653.firebasestorage.app',
    iosBundleId: 'com.example.petGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQhroJ61rnqYeCg24UxvmI-lzTV51POg',
    appId: '1:1016858793515:ios:d7edda7b24aa47d1fefc6e',
    messagingSenderId: '1016858793515',
    projectId: 'petgram-26653',
    storageBucket: 'petgram-26653.firebasestorage.app',
    iosBundleId: 'com.example.petGram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArkxc3sNimm2YklQkJFRIb-lXi0yKQvLM',
    appId: '1:1016858793515:web:19a98bccd27ee264fefc6e',
    messagingSenderId: '1016858793515',
    projectId: 'petgram-26653',
    authDomain: 'petgram-26653.firebaseapp.com',
    storageBucket: 'petgram-26653.firebasestorage.app',
    measurementId: 'G-Y4BHM5VGT4',
  );
}
